name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: |
        echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build and push Vote image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/vote:latest ./vote
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/vote:latest

    - name: Build and push Result image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/result:latest ./result
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/result:latest

    - name: Build and push Worker image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/worker:latest ./worker
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/worker:latest

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig --name eks-kingsly --region eu-central-1

    - name: Deploy to EKS
      run: |
        kubectl apply -f k8s/
        kubectl rollout status deployment/vote
        kubectl rollout status deployment/result
        kubectl rollout status deployment/worker
